import type { Root as HastRoot, Element } from 'hast';
import type { Root as MdastRoot } from 'mdast';
import rehypeAutolinkHeadings from 'rehype-autolink-headings';
import rehypeRaw from 'rehype-raw';
import rehypeSanitize from 'rehype-sanitize';
import rehypeSlug from 'rehype-slug';
import remarkFrontmatter from 'remark-frontmatter';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import remarkParse from 'remark-parse';
import remarkRehype from 'remark-rehype';
import { unified } from 'unified';
import { visit } from 'unist-util-visit';
import { guardUrls } from './plugins/guard-urls';
import { handleImages } from './plugins/images';
import { hardenLinks } from './plugins/harden-links';
import { highlight } from './plugins/highlight';
import { math } from './plugins/math';
import { extractMermaid } from './plugins/mermaid';
import { convertTaskCheckboxes } from './plugins/task-lists';
import { sanitizeSchema } from './sanitize-schema';
import type { BlockedResource, Heading, RenderOptions, RenderResult } from './types';

/**
 * The Markdown pipeline.
 *
 * Two properties are deliberate and should survive refactoring:
 *
 * 1. **Async by interface, synchronous in fact.** Nothing here needs to be
 *    async today — unified runs fast enough on the main thread for the
 *    documents people actually open. The Promise exists so the whole pipeline
 *    can move into a Web Worker in M5 without touching a single call site.
 *    Don't "simplify" it to a sync return.
 *
 * 2. **Sanitize, then generate.** Everything derived from the document is
 *    sanitized first; everything LocalMD generates — heading anchors, task
 *    checkboxes, link hardening, and later KaTeX and Shiki — is added
 *    afterwards. Our own output is built from text, not from document HTML, so
 *    it needs no sanitizing and would be damaged by it. Moving a plugin across
 *    that line is a security change.
 */

/** Captures raw frontmatter before remark-rehype discards the node. */
function captureFrontmatter(sink: { value: string | null }) {
  return (tree: MdastRoot): void => {
    visit(tree, 'yaml', (node: { value?: string }) => {
      sink.value = node.value ?? '';
    });
  };
}

function textOf(node: Element): string {
  let text = '';
  visit(node, 'text', (child: { value: string }) => {
    text += child.value;
  });
  return text.trim();
}

/** Collects headings after slugs exist, for the outline and the palette. */
function collectHeadings(sink: Heading[]) {
  return (tree: HastRoot): void => {
    visit(tree, 'element', (node: Element) => {
      const match = /^h([1-6])$/.exec(node.tagName);
      if (!match?.[1]) return;

      const id = node.properties?.['id'];
      sink.push({
        depth: Number(match[1]),
        text: textOf(node),
        id: typeof id === 'string' ? id : '',
      });
    });
  };
}

export async function renderMarkdown(
  source: string,
  options: RenderOptions = {},
): Promise<RenderResult> {
  const frontmatter = { value: null as string | null };
  const headings: Heading[] = [];
  const blocked: BlockedResource[] = [];

  const processor = unified()
    .use(remarkParse)
    .use(remarkFrontmatter, ['yaml'])
    .use(captureFrontmatter, frontmatter)
    .use(remarkGfm)
    // Single-dollar inline math is OFF. With it on, remark-math reads
    // `$5.00 and $6.00` as a math span and renders it as mangled glyphs — and
    // prices, `$PATH`, `$HOME`, and `${VAR}` are far more common in the
    // documents this product targets than inline LaTeX is.
    //
    // Silently corrupting ordinary prose is a worse failure for a *reader* than
    // requiring `$$x$$` for inline math, which still works. Revisit only with a
    // per-document toggle, never by flipping this back on globally.
    .use(remarkMath, { singleDollarTextMath: false })
    // allowDangerousHtml keeps raw HTML as raw nodes for rehype-raw to parse
    // properly. It is only "dangerous" until sanitization, three steps below.
    .use(remarkRehype, { allowDangerousHtml: true })
    .use(rehypeRaw)
    // ---- everything above this line is untrusted ----
    .use(guardUrls)
    .use(rehypeSanitize, sanitizeSchema)
    // ---- everything below this line is generated by us ----
    .use(convertTaskCheckboxes)
    .use(rehypeSlug)
    .use(rehypeAutolinkHeadings, {
      behavior: 'wrap',
      properties: { className: ['lmd-heading-anchor'] },
    })
    .use(collectHeadings, headings)
    // Math, highlighting, and diagram extraction each load their dependency
    // only if the document actually contains that construct — see the plugins.
    .use(math)
    .use(extractMermaid)
    .use(highlight)
    .use(handleImages, { allowRemote: options.allowRemoteContent === true, blocked })
    .use(hardenLinks);

  // `run`, not `runSync`: Shiki and KaTeX are loaded on demand, which makes
  // their transformers async. This is why the exported function has always
  // returned a Promise.
  const tree = (await processor.run(processor.parse(source))) as HastRoot;

  return { tree, frontmatter: frontmatter.value, headings, blocked };
}
