import { defaultSchema } from 'rehype-sanitize';
import type { Options as SanitizeSchema } from 'rehype-sanitize';

/**
 * LocalMD's sanitization allowlist.
 *
 * Markdown is untrusted input. The stance from the plan: support slightly less
 * Markdown rather than weaken the security model. Raw HTML is sanitized rather
 * than stripped, because READMEs genuinely depend on `<details>`, `<kbd>`,
 * `<img align>`, and `<p align="center">` — stripping HTML would make the
 * single most common use case render badly.
 *
 * The expected failure mode is drift: loosening this one feature request at a
 * time until it means nothing. test/security/sanitize.test.ts is the gate.
 * Changing anything here should require a test to change with it.
 *
 * Ordering matters as much as content. This runs AFTER rehype-raw (so embedded
 * HTML has been parsed into real nodes and cannot smuggle anything past a
 * string-level check) and BEFORE anything that generates our own markup —
 * heading anchors, link hardening, KaTeX, Shiki. Their output is generated by
 * us from text, not supplied by the document, so it does not need sanitizing
 * and would be damaged by it.
 */

const ALLOWED_TAGS = [
  // Structure
  'p', 'br', 'hr', 'div', 'span', 'section',
  'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
  'blockquote', 'pre', 'code',
  // Inline
  'em', 'strong', 'del', 'ins', 'sub', 'sup', 'abbr', 'kbd', 'mark', 'small', 'q', 'cite',
  // Links and media
  'a', 'img', 'picture', 'source',
  // Lists
  'ul', 'ol', 'li', 'dl', 'dt', 'dd',
  // Tables
  'table', 'thead', 'tbody', 'tfoot', 'tr', 'th', 'td', 'caption', 'colgroup', 'col',
  // Disclosure — heavily used in READMEs
  'details', 'summary',
  // Permitted only so GFM task-list checkboxes survive to be converted into
  // inert spans immediately afterwards. See plugins/task-lists.ts — no <input>
  // reaches the rendered output.
  'input',
];

/**
 * Deliberately absent, with reasons:
 *
 *   script, style, link, meta, base  — execution, exfiltration via CSS, or
 *                                      hijacking every relative URL
 *   iframe, object, embed, portal    — arbitrary embedded content
 *   form, input, button, select,     — credential phishing and exfil on submit.
 *   textarea, label, fieldset          GFM task-list checkboxes are converted
 *                                      to inert spans before this runs, so no
 *                                      <input> ever needs to survive
 *   svg and all its children         — XSS via <script>, <animate>, <set>, and
 *                                      <foreignObject>. Mermaid's generated SVG
 *                                      is ours and is inserted separately
 *   math/MathML                      — KaTeX output is generated post-sanitize
 *   audio, video, track              — remote media; no use case in v1
 *   noscript, template, slot         — parser-confusion surface, no benefit
 */

export const sanitizeSchema: SanitizeSchema = {
  ...defaultSchema,

  tagNames: ALLOWED_TAGS,

  attributes: {
    // `className` is allowed broadly because GFM output and code fences depend
    // on it. Classes in LocalMD's reserved `lmd-` namespace are stripped before
    // this point, so user content cannot impersonate application UI.
    '*': ['className', 'id', 'title', 'dir', 'lang'],

    a: ['href', 'name', 'dataFootnoteRef', 'dataFootnoteBackref', 'ariaLabel'],
    img: ['src', 'alt', 'width', 'height', 'align', 'loading', 'decoding'],
    source: ['srcSet', 'media', 'type'],

    // `align` on block elements is the <p align="center"> README idiom.
    p: ['align'],
    div: ['align'],
    h1: ['align'], h2: ['align'], h3: ['align'], h4: ['align'], h5: ['align'], h6: ['align'],

    th: ['align', 'colSpan', 'rowSpan', 'scope'],
    td: ['align', 'colSpan', 'rowSpan'],
    col: ['span', 'width'],
    colgroup: ['span'],

    ol: ['start', 'reversed', 'type'],
    li: ['value'],

    details: ['open'],
    section: ['dataFootnotes'],
    // Preserved so the renderer can pick a highlighter grammar in M2.
    code: ['className'],

    abbr: ['title'],
    q: ['cite'],
    blockquote: ['cite'],

    // Checkbox only, and only the attributes needed to carry its state across
    // the boundary. Anything else — name, value, formaction — is dropped.
    input: [['type', 'checkbox'], 'checked', 'disabled'],
  },

  protocols: {
    href: ['http', 'https', 'mailto'],
    // `data` is permitted here only because guard-urls.ts has already removed
    // every data: URI that isn't a raster image. Sanitize checks the scheme;
    // it cannot check the MIME type.
    src: ['http', 'https', 'data'],
    srcSet: ['http', 'https', 'data'],
    cite: ['http', 'https'],
  },

  // Prefix user-supplied ids/names so document content cannot clobber DOM
  // properties or collide with the heading anchors we generate afterwards.
  clobberPrefix: 'user-content-',
  clobber: ['name', 'id'],

  // Anything not explicitly allowed is dropped rather than unwrapped, so a
  // hostile element cannot leak its children into a trusted position.
  strip: ['script', 'style', 'iframe', 'object', 'embed', 'form', 'svg', 'math'],
};
